//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cwiczenie_przed_sprawdzianem_maj_2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ludzie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Wiek { get; set; }
        public Nullable<bool> MK { get; set; }
    }
}
