//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lotto_21_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewTable
    {
        public int Id { get; set; }
        public Nullable<int> liczba1 { get; set; }
        public Nullable<int> liczba2 { get; set; }
        public Nullable<int> liczba3 { get; set; }
        public Nullable<int> liczba4 { get; set; }
        public Nullable<int> liczba5 { get; set; }
        public Nullable<int> liczba6 { get; set; }
    }
}
